(PC-18308) ci(e2e): added e2e environment

diff --git a/.github/workflows/e2e-android-browser.yml b/.github/workflows/e2e-android-browser.yml
--- a/.github/workflows/e2e-android-browser.yml
+++ b/.github/workflows/e2e-android-browser.yml
@@ -3,14 +3,182 @@ name: Tests e2e Android Browser
 on:
   workflow_dispatch:
     inputs:
-      tbd:
-        description: "tbd"
-        required: false
-        type: string
+      wdio-demo:
+        type: boolean
+        description: WebdriverIO demo - All other params will be ignored
+        required: true
+        default: false
+      environment:
+        type: environment
+        description: Select the environment
+        required: true
+        default: staging
+      build-local:
+        type: boolean
+        description: if true it will run the webapp locally
+        default: false
 
 jobs:
-  tbd:
-    runs-on: ubuntu-latest
+  e2e-android-browser:
+    strategy:
+      matrix:
+        include:
+          - chromedriverVersion: "74.0.3729.6"
+            apiLevel: 29
+            emuTag: google_apis
+            arch: x86
+            profile: Nexus 6P
+    env:
+      CI: true
+      ANDROID_DEVICE_NAME: Nexus6P
+      APPIUM_TEST_SERVER_PORT: 4723
+      APPIUM_TEST_SERVER_HOST: 127.0.0.1
+      DEV_TEST_SERVER_HOST: localhost
+      DEV_TEST_SERVER_PORT: 3000
+      DEV_TEST_SERVER_STARTUP_TIMEOUT_SEC: 60
+      _FORCE_LOGS: 1
+      WDIO_DEMO: ${{ inputs.wdio-demo }}
+      BUILD_LOCAL: ${{ inputs.build-local }}
+      ENVIRONMENT: ${{ inputs.environment }}
+    # No hardware acceleration is available for emulators on Ubuntu:
+    # https://github.com/marketplace/actions/android-emulator-runner#can-i-use-this-action-on-linux-vms
+    runs-on: macos-latest
+    environment: ${{ inputs.environment }}
     steps:
-      - name: Hello World
-        run: echo "Hello World"
+
+      - run: |
+          echo "WDIO_DEMO: $WDIO_DEMO"
+          echo "BUILD_LOCAL: $BUILD_LOCAL"
+          echo "ENVIRONMENT: $ENVIRONMENT"
+
+      - uses: actions/checkout@v3
+
+      - uses: actions/setup-node@v3
+        with:
+          node-version-file: '.nvmrc'
+
+      - uses: actions/setup-java@v3
+        with:
+          distribution: 'temurin'
+          java-version: '11'
+
+      - name: Install dependencies
+        run: yarn install
+
+      - name: Download WebdriverIO demo
+        if: ${{ env.WDIO_DEMO == 'true' }}
+        run: yarn e2e:install.demo
+
+      - name: Install extraneous dev dependencies
+        run: |
+          npm config set legacy-peer-deps true
+          npm install -g appium@next
+          npm install --chromedriver_version="${{ matrix.chromedriverVersion }}"
+          npm install --no-save mjpeg-consumer
+          appium driver install uiautomator2
+
+      - name: Sets WDIO_BASE_URL for local or distributed Web app
+        if: ${{ env.WDIO_DEMO == 'false' }}
+        run: |
+          if [[ "${{ env.BUILD_LOCAL }}" = "true" ]]; then
+            echo "WDIO_BASE_URL=http://${{ env.DEV_TEST_SERVER_HOST }}:${{ env.DEV_TEST_SERVER_PORT }}" >> $GITHUB_ENV
+          elif [[ "${{ env.ENVIRONMENT }}" = "testing" ]]; then
+            echo "WDIO_BASE_URL=https://app.testing.passculture.team" >> $GITHUB_ENV
+          elif [[ "${{ env.ENVIRONMENT }}" = "staging" ]]; then
+            echo "WDIO_BASE_URL=https://app.staging.passculture.team" >> $GITHUB_ENV
+          fi
+
+      ## Local
+
+      - name: Start Local dev server ${{ inputs.environment }}
+        if: ${{ (env.WDIO_DEMO == 'false') && (env.BUILD_LOCAL == 'true') }}
+        run: |
+          cwd=$(pwd)
+          pushd "$cwd"
+          nohup yarn start:web:${{ env.ENVIRONMENT }} \
+            2>&1 > "$cwd/webpack-dev-server.log" &
+          popd
+
+#      - name: Wait for Local dev server ${{ inputs.environment }} to startup
+#        if: ${{ (env.WDIO_DEMO == 'false') && (env.BUILD_LOCAL == 'true') }}
+#        run: |
+#          seconds_started=$(date +%s)
+#          until curl -s -f -o /dev/null "${{ env.WDIO_BASE_URL }}"
+#          do
+#            sleep 0.1
+#            seconds_elapsed=$(( $(date +%s) - seconds_started ))
+#            if [[ $seconds_elapsed -gt ${{ env.DEV_TEST_SERVER_STARTUP_TIMEOUT_SEC }} ]]; then
+#              echo "Local dev server was unable to start within ${{ env.DEV_TEST_SERVER_STARTUP_TIMEOUT_SEC }} seconds timeout"
+#              exit 1
+#            fi
+#          done
+
+
+      ## Common
+      - name: Start Appium server
+        run: |
+          cwd=$(pwd)
+          pushd "$cwd"
+          cd ~
+          nohup appium server \
+            --port=$APPIUM_TEST_SERVER_PORT \
+            --address=$APPIUM_TEST_SERVER_HOST \
+            --relaxed-security \
+            2>&1 > "$cwd/appium.log" &
+          popd
+
+#      - name: Wait for Appium server startup
+#        run: |
+#          seconds_started=$(date +%s)
+#          while ! nc -z $APPIUM_TEST_SERVER_HOST $APPIUM_TEST_SERVER_PORT; do
+#            sleep 0.1
+#            seconds_elapsed=$(( $(date +%s) - seconds_started ))
+#            if [[ $seconds_elapsed -gt $APPIUM_STARTUP_TIMEOUT_SEC ]]; then
+#              echo "Appium server was unable to start within $APPIUM_STARTUP_TIMEOUT_SEC seconds timeout"
+#              exit 1
+#            fi
+#          done
+
+      - run: nohup adb logcat > logcat.log &
+        name: Capture logcat
+
+      - uses: reactivecircus/android-emulator-runner@v2
+        name: e2e_api${{ matrix.apiLevel }}
+        with:
+          script: yarn e2e:android.browser
+          avd-name: ${{ env.ANDROID_DEVICE_NAME }}
+          sdcard-path-or-size: 1500M
+          api-level: ${{ matrix.apiLevel }}
+          disable-spellchecker: true
+          target: ${{ matrix.emuTag }}
+          arch: ${{ matrix.arch }}
+          profile: ${{ matrix.profile }}
+
+      - name: Save logcat output
+        if: ${{ always() }}
+        uses: actions/upload-artifact@master
+        with:
+          name: logcat-api${{ matrix.apiLevel }}
+          path: logcat.log
+
+      - name: Save server output
+        if: ${{ always() }}
+        uses: actions/upload-artifact@master
+        with:
+          name: appium-api${{ matrix.apiLevel }}
+          path: appium.log
+
+      - name: Show appium server output
+        if: ${{ always() }}
+        run: cat appium.log
+
+      - name: Save dev server output
+        if: ${{ (always()) && (env.WDIO_DEMO == 'false') && (env.BUILD_LOCAL == 'local') }}
+        uses: actions/upload-artifact@master
+        with:
+          name: webpack-dev-server{{ matrix.apiLevel }}
+          path: webpack-dev-server.log
+
+      - name: Show dev server output
+        if: ${{ (always()) && (env.WDIO_DEMO == 'false') && (env.BUILD_LOCAL == 'local') }}
+        run: cat webpack-dev-server.log
