e2e-ios-native.yml

diff --git a/.github/workflows/e2e-ios-safari.yml b/.github/workflows/e2e-ios-safari.yml
--- a/.github/workflows/e2e-ios-safari.yml
+++ b/.github/workflows/e2e-ios-safari.yml
@@ -8,9 +8,56 @@ on:
         required: false
         type: string
 
+
 jobs:
-  tbd:
-    runs-on: ubuntu-latest
+  e2e-ios-safari:
+    env:
+      CI: true
+      APPIUM_TEST_SERVER_PORT: 4723
+      APPIUM_TEST_SERVER_HOST: 0.0.0.0
+      APPIUM_STARTUP_TIMEOUT_SEC: 30
+      _FORCE_LOGS: 1
+    runs-on: macos-latest
     steps:
-      - name: Hello World
-        run: echo "Hello World"
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version-file: '.nvmrc'
+      - run: yarn install
+      - run: |
+          npm config set legacy-peer-deps true
+          npm install -g appium@next
+          npm install -g appium-doctor
+        name: Install dev dependencies
+      - run: |
+          cwd=$(pwd)
+          pushd "$cwd"
+          cd ~
+          appium driver install xcuitest
+          appium driver install safari
+          nohup appium server \
+            --port=$APPIUM_TEST_SERVER_PORT \
+            --address=$APPIUM_TEST_SERVER_HOST \
+            --relaxed-security \
+            2>&1 > "$cwd/appium.log" &
+          popd
+        name: Start Appium server
+      - run: |
+          seconds_started=$(date +%s)
+          while ! nc -z $APPIUM_TEST_SERVER_HOST $APPIUM_TEST_SERVER_PORT; do
+            sleep 0.1
+            seconds_elapsed=$(( $(date +%s) - seconds_started ))
+            if [[ $seconds_elapsed -gt $APPIUM_STARTUP_TIMEOUT_SEC ]]; then
+              echo "Appium server was unable to start within $APPIUM_STARTUP_TIMEOUT_SEC seconds timeout"
+              exit 1
+            fi
+          done
+        name: Wait for Appium server startup
+      - run: yarn ios.browser
+        name: Run functional tests
+      - name: Save server output
+        if: ${{ always() }}
+        uses: actions/upload-artifact@master
+        with:
+          name: appium.log
+          path: appium.log
